"""add_units_and_conference_models"""

revision = '092715b26998'
down_revision = '0493269b9c4e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_unit_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_unit_member_id'), 'archived_unit_member', ['id'], unique=False)
    op.create_index(op.f('ix_archived_unit_member_registered_user_id'), 'archived_unit_member', ['registered_user_id'], unique=False)
    op.create_table('food_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('veg_count', sa.Integer(), nullable=True),
    sa.Column('non_veg_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_preference_conference_id'), 'food_preference', ['conference_id'], unique=False)
    op.create_index(op.f('ix_food_preference_id'), 'food_preference', ['id'], unique=False)
    op.create_index(op.f('ix_food_preference_uploaded_by_id'), 'food_preference', ['uploaded_by_id'], unique=False)
    op.create_table('removed_unit_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_removed_unit_member_id'), 'removed_unit_member', ['id'], unique=False)
    op.create_index(op.f('ix_removed_unit_member_registered_user_id'), 'removed_unit_member', ['registered_user_id'], unique=False)
    op.create_table('unit_member_add_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('proof', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_member_add_request_id'), 'unit_member_add_request', ['id'], unique=False)
    op.create_index(op.f('ix_unit_member_add_request_registered_user_id'), 'unit_member_add_request', ['registered_user_id'], unique=False)
    op.create_table('unit_member_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('original_gender', sa.String(length=10), nullable=True),
    sa.Column('original_dob', sa.Date(), nullable=True),
    sa.Column('original_blood_group', sa.String(length=10), nullable=True),
    sa.Column('original_qualification', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('proof', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_member_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_member_change_request_id'), 'unit_member_change_request', ['id'], unique=False)
    op.create_index(op.f('ix_unit_member_change_request_unit_member_id'), 'unit_member_change_request', ['unit_member_id'], unique=False)
    op.create_table('unit_officials_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_official_id', sa.Integer(), nullable=False),
    sa.Column('president_designation', sa.String(length=50), nullable=True),
    sa.Column('original_president_designation', sa.String(length=50), nullable=True),
    sa.Column('president_name', sa.String(length=255), nullable=True),
    sa.Column('original_president_name', sa.String(length=255), nullable=True),
    sa.Column('president_phone', sa.String(length=30), nullable=True),
    sa.Column('original_president_phone', sa.String(length=30), nullable=True),
    sa.Column('vice_president_name', sa.String(length=255), nullable=True),
    sa.Column('original_vice_president_name', sa.String(length=255), nullable=True),
    sa.Column('vice_president_phone', sa.String(length=30), nullable=True),
    sa.Column('original_vice_president_phone', sa.String(length=30), nullable=True),
    sa.Column('secretary_name', sa.String(length=255), nullable=True),
    sa.Column('original_secretary_name', sa.String(length=255), nullable=True),
    sa.Column('secretary_phone', sa.String(length=30), nullable=True),
    sa.Column('original_secretary_phone', sa.String(length=30), nullable=True),
    sa.Column('joint_secretary_name', sa.String(length=255), nullable=True),
    sa.Column('original_joint_secretary_name', sa.String(length=255), nullable=True),
    sa.Column('joint_secretary_phone', sa.String(length=30), nullable=True),
    sa.Column('original_joint_secretary_phone', sa.String(length=30), nullable=True),
    sa.Column('treasurer_name', sa.String(length=255), nullable=True),
    sa.Column('original_treasurer_name', sa.String(length=255), nullable=True),
    sa.Column('treasurer_phone', sa.String(length=30), nullable=True),
    sa.Column('original_treasurer_phone', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('proof', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_official_id'], ['unit_officials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_officials_change_request_id'), 'unit_officials_change_request', ['id'], unique=False)
    op.create_index(op.f('ix_unit_officials_change_request_unit_official_id'), 'unit_officials_change_request', ['unit_official_id'], unique=False)
    op.create_table('unit_transfer_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_member_id', sa.Integer(), nullable=False),
    sa.Column('current_unit_id', sa.Integer(), nullable=True),
    sa.Column('original_registered_user_id', sa.Integer(), nullable=True),
    sa.Column('destination_unit_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('proof', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_unit_id'], ['unit_name.id'], ),
    sa.ForeignKeyConstraint(['destination_unit_id'], ['unit_name.id'], ),
    sa.ForeignKeyConstraint(['original_registered_user_id'], ['custom_user.id'], ),
    sa.ForeignKeyConstraint(['unit_member_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_transfer_request_id'), 'unit_transfer_request', ['id'], unique=False)
    op.create_index(op.f('ix_unit_transfer_request_unit_member_id'), 'unit_transfer_request', ['unit_member_id'], unique=False)
    op.create_table('unit_councilor_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_councilor_id', sa.Integer(), nullable=False),
    sa.Column('unit_member_id', sa.Integer(), nullable=True),
    sa.Column('original_unit_member_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('proof', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_unit_member_id'], ['unit_members.id'], ),
    sa.ForeignKeyConstraint(['unit_councilor_id'], ['unit_councilor.id'], ),
    sa.ForeignKeyConstraint(['unit_member_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_councilor_change_request_id'), 'unit_councilor_change_request', ['id'], unique=False)
    op.create_index(op.f('ix_unit_councilor_change_request_unit_councilor_id'), 'unit_councilor_change_request', ['unit_councilor_id'], unique=False)
    op.drop_index(op.f('idx_24617_auth_app_unitcouncil_registered_user_id_ea628aa8_fk_a'), table_name='auth_app_unitcouncilor')
    op.drop_index(op.f('idx_24617_auth_app_unitcouncil_unit_member_id_e7f5e3b4_fk_auth_'), table_name='auth_app_unitcouncilor')
    op.drop_table('auth_app_unitcouncilor')
    op.drop_table('auth_app_clergydistrict')
    op.drop_index(op.f('idx_24837_kalamela_individuale_added_by_id_55be7493_fk_auth_app'), table_name='kalamela_individualeventparticipation')
    op.drop_index(op.f('idx_24837_kalamela_individuale_individual_event_id_d029d03b_fk_'), table_name='kalamela_individualeventparticipation')
    op.drop_index(op.f('idx_24837_kalamela_individuale_participant_id_c03094b9_fk_auth_'), table_name='kalamela_individualeventparticipation')
    op.drop_table('kalamela_individualeventparticipation')
    op.drop_index(op.f('idx_24744_conference_conferenc_conference_id_341b2b27_fk_confer'), table_name='conference_conferencedelegate')
    op.drop_index(op.f('idx_24744_conference_conferenc_members_id_fb62d2b7_fk_auth_app_'), table_name='conference_conferencedelegate')
    op.drop_index(op.f('idx_24744_conference_conferenc_officials_id_9a8b2622_fk_auth_ap'), table_name='conference_conferencedelegate')
    op.drop_table('conference_conferencedelegate')
    op.drop_table('kalamela_groupevent')
    op.drop_index(op.f('idx_24732_auth_permission_content_type_id_codename_01ab375a_uni'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('idx_24785_django_session_expire_date_a5c62663'), table_name='django_session')
    op.drop_table('django_session')
    op.drop_index(op.f('idx_24591_auth_app_customuser_clergy_district_id_5c7bc652_fk_au'), table_name='auth_app_customuser')
    op.drop_index(op.f('idx_24591_auth_app_customuser_conference_id_b982c4bf_fk_confere'), table_name='auth_app_customuser')
    op.drop_index(op.f('idx_24591_auth_app_customuser_email_0f7acc77_uniq'), table_name='auth_app_customuser')
    op.drop_index(op.f('idx_24591_auth_app_customuser_unit_name_id_d460adf5_fk_auth_app'), table_name='auth_app_customuser')
    op.drop_index(op.f('idx_24591_username'), table_name='auth_app_customuser')
    op.drop_table('auth_app_customuser')
    op.drop_index(op.f('idx_24791_kalamela_appeal_added_by_id_c86c080e_fk_auth_app_unit'), table_name='kalamela_appeal')
    op.drop_table('kalamela_appeal')
    op.drop_index(op.f('idx_24681_auth_app_unitofficia_unit_official_id_02e242ed_fk_aut'), table_name='auth_app_unitofficialschangerequest')
    op.drop_table('auth_app_unitofficialschangerequest')
    op.drop_table('conference_conference')
    op.drop_index(op.f('idx_24629_auth_app_unitdetails_registered_user_id_2cda4c7a_fk_a'), table_name='auth_app_unitdetails')
    op.drop_table('auth_app_unitdetails')
    op.drop_index(op.f('idx_24710_auth_app_unitregistr_registered_user_id_1dfbb9c6_fk_a'), table_name='auth_app_unitregistrationdata')
    op.drop_table('auth_app_unitregistrationdata')
    op.drop_index(op.f('idx_24578_auth_app_archiveduni_registered_user_id_c46d5320_fk_a'), table_name='auth_app_archivedunitmember')
    op.drop_table('auth_app_archivedunitmember')
    op.drop_index(op.f('idx_24749_conference_conferenc_conference_id_f9c3fd7c_fk_confer'), table_name='conference_conferencepayment')
    op.drop_index(op.f('idx_24749_conference_conferenc_uploaded_by_id_177197ed_fk_auth_'), table_name='conference_conferencepayment')
    op.drop_table('conference_conferencepayment')
    op.drop_index(op.f('idx_24715_auth_app_unittransfe_current_unit_id_355b3b2b_fk_auth'), table_name='auth_app_unittransferrequest')
    op.drop_index(op.f('idx_24715_auth_app_unittransfe_destination_unit_id_965f3375_fk_'), table_name='auth_app_unittransferrequest')
    op.drop_index(op.f('idx_24715_auth_app_unittransfe_original_registered__5a4988e1_fk'), table_name='auth_app_unittransferrequest')
    op.drop_index(op.f('idx_24715_auth_app_unittransfe_unit_member_id_82e1f938_fk_auth_'), table_name='auth_app_unittransferrequest')
    op.drop_table('auth_app_unittransferrequest')
    op.drop_index(op.f('idx_24722_name'), table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_table('django_migrations')
    op.drop_index(op.f('idx_24668_auth_app_unitname_clergy_district_id_b4cf9464_fk_auth'), table_name='auth_app_unitname')
    op.drop_table('auth_app_unitname')
    op.drop_index(op.f('idx_24799_kalamela_appealpayem_appeal_id_e219c9cd_fk_kalamela_'), table_name='kalamela_appealpayements')
    op.drop_table('kalamela_appealpayements')
    op.drop_table('kalamela_groupeventscorecard')
    op.drop_index(op.f('idx_24843_kalamela_individuale_event_participation__263c65ac_fk'), table_name='kalamela_individualeventscorecard')
    op.drop_index(op.f('idx_24843_kalamela_individuale_participant_id_43081941_fk_auth_'), table_name='kalamela_individualeventscorecard')
    op.drop_table('kalamela_individualeventscorecard')
    op.drop_index(op.f('idx_24727_auth_group_permissio_permission_id_84c5c92e_fk_auth_p'), table_name='auth_group_permissions')
    op.drop_index(op.f('idx_24727_auth_group_permissions_group_id_permission_id_0cd325b'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('idx_24622_auth_app_unitcouncil_original_unit_member_c14ed692_fk'), table_name='auth_app_unitcouncilorchangerequest')
    op.drop_index(op.f('idx_24622_auth_app_unitcouncil_unit_councilor_id_d5b3c4a8_fk_au'), table_name='auth_app_unitcouncilorchangerequest')
    op.drop_index(op.f('idx_24622_auth_app_unitcouncil_unit_member_id_0c703263_fk_auth_'), table_name='auth_app_unitcouncilorchangerequest')
    op.drop_table('auth_app_unitcouncilorchangerequest')
    op.drop_index(op.f('idx_24609_auth_app_removedunit_registered_user_id_14e94446_fk_a'), table_name='auth_app_removedunitmember')
    op.drop_table('auth_app_removedunitmember')
    op.drop_index(op.f('idx_24604_auth_app_customuser__permission_id_0ed30c88_fk_auth_p'), table_name='auth_app_customuser_user_permissions')
    op.drop_index(op.f('idx_24604_auth_app_customuser_user_customuser_id_permission_fd5'), table_name='auth_app_customuser_user_permissions')
    op.drop_table('auth_app_customuser_user_permissions')
    op.drop_index(op.f('idx_24812_kalamela_groupeventp_added_by_id_0ba673eb_fk_auth_app'), table_name='kalamela_groupeventparticipation')
    op.drop_index(op.f('idx_24812_kalamela_groupeventp_group_event_id_da401309_fk_kalam'), table_name='kalamela_groupeventparticipation')
    op.drop_index(op.f('idx_24812_kalamela_groupeventp_participant_id_8d5163e2_fk_auth_'), table_name='kalamela_groupeventparticipation')
    op.drop_table('kalamela_groupeventparticipation')
    op.drop_table('kalamela_individualevent')
    op.drop_index(op.f('idx_24854_kalamela_kalamelapay_paid_by_id_ba8c4a46_fk_auth_app_'), table_name='kalamela_kalamelapayements')
    op.drop_table('kalamela_kalamelapayements')
    op.drop_index(op.f('idx_24757_conference_conferenc_district_official_id_50c5a833_fk'), table_name='conference_conferenceregistrationdata')
    op.drop_table('conference_conferenceregistrationdata')
    op.drop_index(op.f('idx_24673_auth_app_unitofficia_registered_user_id_4f43f0c0_fk_a'), table_name='auth_app_unitofficials')
    op.drop_table('auth_app_unitofficials')
    op.drop_index(op.f('idx_24634_auth_app_unitmembera_registered_user_id_c46a149e_fk_a'), table_name='auth_app_unitmemberaddrequest')
    op.drop_table('auth_app_unitmemberaddrequest')
    op.drop_index(op.f('idx_24660_auth_app_unitmembers_registered_user_id_216007fa_fk_a'), table_name='auth_app_unitmembers')
    op.drop_table('auth_app_unitmembers')
    op.drop_index(op.f('idx_24645_auth_app_unitmemberc_unit_member_id_d68f7ef8_fk_auth_'), table_name='auth_app_unitmemberchangerequest')
    op.drop_table('auth_app_unitmemberchangerequest')
    op.drop_index(op.f('idx_24762_conference_foodprefe_conference_id_daa8ce0d_fk_confer'), table_name='conference_foodpreference')
    op.drop_index(op.f('idx_24762_conference_foodprefe_uploaded_by_id_6bc50322_fk_auth_'), table_name='conference_foodpreference')
    op.drop_table('conference_foodpreference')
    op.drop_index(op.f('idx_24599_auth_app_customuser_groups_customuser_id_group_id_eef'), table_name='auth_app_customuser_groups')
    op.drop_index(op.f('idx_24599_auth_app_customuser_groups_group_id_951c60f2_fk_auth_'), table_name='auth_app_customuser_groups')
    op.drop_table('auth_app_customuser_groups')
    op.drop_index(op.f('idx_24774_django_content_type_app_label_model_76bd3d3b_uniq'), table_name='django_content_type')
    op.drop_table('django_content_type')
    op.drop_index(op.f('idx_24767_django_admin_log_content_type_id_c4bce8eb_fk_django_c'), table_name='django_admin_log')
    op.drop_index(op.f('idx_24767_django_admin_log_user_id_c564eba6_fk_auth_app_customu'), table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_index(op.f('idx_24849_kalamela_kalamelaexc_members_id_9d2d995c_fk_auth_app_'), table_name='kalamela_kalamelaexcludemembers')
    op.drop_table('kalamela_kalamelaexcludemembers')
    op.alter_column('conference', 'details',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('conference', 'status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_delegate_per_conf_official'), 'conference_delegate', type_='unique')
    op.create_index(op.f('ix_conference_delegate_conference_id'), 'conference_delegate', ['conference_id'], unique=False)
    op.create_index(op.f('ix_conference_delegate_id'), 'conference_delegate', ['id'], unique=False)
    op.create_index(op.f('ix_conference_delegate_members_id'), 'conference_delegate', ['members_id'], unique=False)
    op.create_index(op.f('ix_conference_delegate_officials_id'), 'conference_delegate', ['officials_id'], unique=False)
    op.add_column('conference_payment', sa.Column('proof', sa.String(length=500), nullable=True))
    op.alter_column('conference_payment', 'amount_to_pay',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('conference_payment', 'uploaded_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conference_payment', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROOF_UPLOADED', 'PAID', 'DECLINED', name='paymentstatus'),
               type_=sa.String(length=20),
               nullable=True)
    op.create_index(op.f('ix_conference_payment_conference_id'), 'conference_payment', ['conference_id'], unique=False)
    op.create_index(op.f('ix_conference_payment_id'), 'conference_payment', ['id'], unique=False)
    op.create_index(op.f('ix_conference_payment_uploaded_by_id'), 'conference_payment', ['uploaded_by_id'], unique=False)
    op.drop_column('conference_payment', 'payment_reference')
    op.drop_column('conference_payment', 'proof_path')
    op.alter_column('conference_registration_data', 'status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('conference_registration_data_district_official_id_key'), 'conference_registration_data', type_='unique')
    op.create_index(op.f('ix_conference_registration_data_district_official_id'), 'conference_registration_data', ['district_official_id'], unique=False)
    op.create_index(op.f('ix_conference_registration_data_id'), 'conference_registration_data', ['id'], unique=False)
    op.add_column('unit_officials', sa.Column('president_designation', sa.String(length=50), nullable=True))
    op.add_column('unit_officials', sa.Column('president_name', sa.String(length=255), nullable=True))
    op.add_column('unit_officials', sa.Column('president_phone', sa.String(length=30), nullable=True))
    op.add_column('unit_officials', sa.Column('vice_president_name', sa.String(length=255), nullable=True))
    op.add_column('unit_officials', sa.Column('vice_president_phone', sa.String(length=30), nullable=True))
    op.add_column('unit_officials', sa.Column('secretary_name', sa.String(length=255), nullable=True))
    op.add_column('unit_officials', sa.Column('secretary_phone', sa.String(length=30), nullable=True))
    op.add_column('unit_officials', sa.Column('joint_secretary_name', sa.String(length=255), nullable=True))
    op.add_column('unit_officials', sa.Column('joint_secretary_phone', sa.String(length=30), nullable=True))
    op.add_column('unit_officials', sa.Column('treasurer_name', sa.String(length=255), nullable=True))
    op.add_column('unit_officials', sa.Column('treasurer_phone', sa.String(length=30), nullable=True))
    op.drop_column('unit_officials', 'president')
    op.drop_column('unit_officials', 'treasurer')
    op.drop_column('unit_officials', 'secretary')
    op.drop_column('unit_officials', 'joint_secretary')
    op.drop_column('unit_officials', 'vice_president')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_officials', sa.Column('vice_president', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('unit_officials', sa.Column('joint_secretary', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('unit_officials', sa.Column('secretary', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('unit_officials', sa.Column('treasurer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('unit_officials', sa.Column('president', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('unit_officials', 'treasurer_phone')
    op.drop_column('unit_officials', 'treasurer_name')
    op.drop_column('unit_officials', 'joint_secretary_phone')
    op.drop_column('unit_officials', 'joint_secretary_name')
    op.drop_column('unit_officials', 'secretary_phone')
    op.drop_column('unit_officials', 'secretary_name')
    op.drop_column('unit_officials', 'vice_president_phone')
    op.drop_column('unit_officials', 'vice_president_name')
    op.drop_column('unit_officials', 'president_phone')
    op.drop_column('unit_officials', 'president_name')
    op.drop_column('unit_officials', 'president_designation')
    op.drop_index(op.f('ix_conference_registration_data_id'), table_name='conference_registration_data')
    op.drop_index(op.f('ix_conference_registration_data_district_official_id'), table_name='conference_registration_data')
    op.create_unique_constraint(op.f('conference_registration_data_district_official_id_key'), 'conference_registration_data', ['district_official_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('conference_registration_data', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.add_column('conference_payment', sa.Column('proof_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('conference_payment', sa.Column('payment_reference', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_conference_payment_uploaded_by_id'), table_name='conference_payment')
    op.drop_index(op.f('ix_conference_payment_id'), table_name='conference_payment')
    op.drop_index(op.f('ix_conference_payment_conference_id'), table_name='conference_payment')
    op.alter_column('conference_payment', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'PROOF_UPLOADED', 'PAID', 'DECLINED', name='paymentstatus'),
               nullable=False)
    op.alter_column('conference_payment', 'uploaded_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conference_payment', 'amount_to_pay',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('conference_payment', 'proof')
    op.drop_index(op.f('ix_conference_delegate_officials_id'), table_name='conference_delegate')
    op.drop_index(op.f('ix_conference_delegate_members_id'), table_name='conference_delegate')
    op.drop_index(op.f('ix_conference_delegate_id'), table_name='conference_delegate')
    op.drop_index(op.f('ix_conference_delegate_conference_id'), table_name='conference_delegate')
    op.create_unique_constraint(op.f('uq_delegate_per_conf_official'), 'conference_delegate', ['conference_id', 'officials_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('conference', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('conference', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               nullable=True)
    op.create_table('kalamela_kalamelaexcludemembers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('members_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['members_id'], ['auth_app_unitmembers.id'], name=op.f('kalamela_kalamelaexc_members_id_9d2d995c_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24849_primary'))
    )
    op.create_index(op.f('idx_24849_kalamela_kalamelaexc_members_id_9d2d995c_fk_auth_app_'), 'kalamela_kalamelaexcludemembers', ['members_id'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_co'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_app_customuser.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_auth_app_customuser_id'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24767_primary'))
    )
    op.create_index(op.f('idx_24767_django_admin_log_user_id_c564eba6_fk_auth_app_customu'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_24767_django_admin_log_content_type_id_c4bce8eb_fk_django_c'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('django_content_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='idx_24774_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_24774_django_content_type_app_label_model_76bd3d3b_uniq'), 'django_content_type', ['app_label', 'model'], unique=True)
    op.create_table('auth_app_customuser_groups',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('customuser_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customuser_id'], ['auth_app_customuser.id'], name=op.f('auth_app_customuser__customuser_id_cfa7c414_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_app_customuser_groups_group_id_951c60f2_fk_auth_group_id'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24599_primary'))
    )
    op.create_index(op.f('idx_24599_auth_app_customuser_groups_group_id_951c60f2_fk_auth_'), 'auth_app_customuser_groups', ['group_id'], unique=False)
    op.create_index(op.f('idx_24599_auth_app_customuser_groups_customuser_id_group_id_eef'), 'auth_app_customuser_groups', ['customuser_id', 'group_id'], unique=True)
    op.create_table('conference_foodpreference',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('veg_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('non_veg_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('conference_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference_conference.id'], name=op.f('conference_foodprefe_conference_id_daa8ce0d_fk_conferenc'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['auth_app_customuser.id'], name=op.f('conference_foodprefe_uploaded_by_id_6bc50322_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24762_primary'))
    )
    op.create_index(op.f('idx_24762_conference_foodprefe_uploaded_by_id_6bc50322_fk_auth_'), 'conference_foodpreference', ['uploaded_by_id'], unique=False)
    op.create_index(op.f('idx_24762_conference_foodprefe_conference_id_daa8ce0d_fk_confer'), 'conference_foodpreference', ['conference_id'], unique=False)
    op.create_table('auth_app_unitmemberchangerequest',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_gender', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('original_dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_blood_group', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('qualification', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_qualification', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('proof', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('unit_member_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['unit_member_id'], ['auth_app_unitmembers.id'], name=op.f('auth_app_unitmemberc_unit_member_id_d68f7ef8_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24645_primary'))
    )
    op.create_index(op.f('idx_24645_auth_app_unitmemberc_unit_member_id_d68f7ef8_fk_auth_'), 'auth_app_unitmemberchangerequest', ['unit_member_id'], unique=False)
    op.create_table('auth_app_unitmembers',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('auth_app_unitmembers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('qualification', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('registered_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['registered_user_id'], ['auth_app_customuser.id'], name='auth_app_unitmembers_registered_user_id_216007fa_fk_auth_app_', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='idx_24660_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_24660_auth_app_unitmembers_registered_user_id_216007fa_fk_a'), 'auth_app_unitmembers', ['registered_user_id'], unique=False)
    op.create_table('auth_app_unitmemberaddrequest',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('qualification', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('proof', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('registered_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['auth_app_customuser.id'], name=op.f('auth_app_unitmembera_registered_user_id_c46a149e_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24634_primary'))
    )
    op.create_index(op.f('idx_24634_auth_app_unitmembera_registered_user_id_c46a149e_fk_a'), 'auth_app_unitmemberaddrequest', ['registered_user_id'], unique=False)
    op.create_table('auth_app_unitofficials',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('auth_app_unitofficials_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('president_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('president_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vice_president_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vice_president_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('secretary_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('secretary_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('joint_secretary_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('joint_secretary_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('treasurer_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('treasurer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registered_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('president_designation', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['registered_user_id'], ['auth_app_customuser.id'], name='auth_app_unitofficia_registered_user_id_4f43f0c0_fk_auth_app_', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='idx_24673_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_24673_auth_app_unitofficia_registered_user_id_4f43f0c0_fk_a'), 'auth_app_unitofficials', ['registered_user_id'], unique=False)
    op.create_table('conference_conferenceregistrationdata',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('district_official_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['district_official_id'], ['auth_app_customuser.id'], name=op.f('conference_conferenc_district_official_id_50c5a833_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24757_primary'))
    )
    op.create_index(op.f('idx_24757_conference_conferenc_district_official_id_50c5a833_fk'), 'conference_conferenceregistrationdata', ['district_official_id'], unique=False)
    op.create_table('kalamela_kalamelapayements',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('individual_events_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('group_events_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total_amount_to_pay', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_proof', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('paid_by_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paid_by_id'], ['auth_app_customuser.id'], name=op.f('kalamela_kalamelapay_paid_by_id_ba8c4a46_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24854_primary'))
    )
    op.create_index(op.f('idx_24854_kalamela_kalamelapay_paid_by_id_ba8c4a46_fk_auth_app_'), 'kalamela_kalamelapayements', ['paid_by_id'], unique=False)
    op.create_table('kalamela_individualevent',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('kalamela_individualevent_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='idx_24829_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_table('kalamela_groupeventparticipation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chest_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('added_by_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['auth_app_customuser.id'], name=op.f('kalamela_groupeventp_added_by_id_0ba673eb_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_event_id'], ['kalamela_groupevent.id'], name=op.f('kalamela_groupeventp_group_event_id_da401309_fk_kalamela_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_id'], ['auth_app_unitmembers.id'], name=op.f('kalamela_groupeventp_participant_id_8d5163e2_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24812_primary'))
    )
    op.create_index(op.f('idx_24812_kalamela_groupeventp_participant_id_8d5163e2_fk_auth_'), 'kalamela_groupeventparticipation', ['participant_id'], unique=False)
    op.create_index(op.f('idx_24812_kalamela_groupeventp_group_event_id_da401309_fk_kalam'), 'kalamela_groupeventparticipation', ['group_event_id'], unique=False)
    op.create_index(op.f('idx_24812_kalamela_groupeventp_added_by_id_0ba673eb_fk_auth_app'), 'kalamela_groupeventparticipation', ['added_by_id'], unique=False)
    op.create_table('auth_app_customuser_user_permissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('customuser_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customuser_id'], ['auth_app_customuser.id'], name=op.f('auth_app_customuser__customuser_id_fdf7c76a_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_app_customuser__permission_id_0ed30c88_fk_auth_perm'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24604_primary'))
    )
    op.create_index(op.f('idx_24604_auth_app_customuser_user_customuser_id_permission_fd5'), 'auth_app_customuser_user_permissions', ['customuser_id', 'permission_id'], unique=True)
    op.create_index(op.f('idx_24604_auth_app_customuser__permission_id_0ed30c88_fk_auth_p'), 'auth_app_customuser_user_permissions', ['permission_id'], unique=False)
    op.create_table('auth_app_removedunitmember',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('qualification', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('registered_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['auth_app_customuser.id'], name=op.f('auth_app_removedunit_registered_user_id_14e94446_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24609_primary'))
    )
    op.create_index(op.f('idx_24609_auth_app_removedunit_registered_user_id_14e94446_fk_a'), 'auth_app_removedunitmember', ['registered_user_id'], unique=False)
    op.create_table('auth_app_unitcouncilorchangerequest',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('proof', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('original_unit_member_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_councilor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('unit_member_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['original_unit_member_id'], ['auth_app_unitmembers.id'], name=op.f('auth_app_unitcouncil_original_unit_member_c14ed692_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_councilor_id'], ['auth_app_unitcouncilor.id'], name=op.f('auth_app_unitcouncil_unit_councilor_id_d5b3c4a8_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_member_id'], ['auth_app_unitmembers.id'], name=op.f('auth_app_unitcouncil_unit_member_id_0c703263_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24622_primary'))
    )
    op.create_index(op.f('idx_24622_auth_app_unitcouncil_unit_member_id_0c703263_fk_auth_'), 'auth_app_unitcouncilorchangerequest', ['unit_member_id'], unique=False)
    op.create_index(op.f('idx_24622_auth_app_unitcouncil_unit_councilor_id_d5b3c4a8_fk_au'), 'auth_app_unitcouncilorchangerequest', ['unit_councilor_id'], unique=False)
    op.create_index(op.f('idx_24622_auth_app_unitcouncil_original_unit_member_c14ed692_fk'), 'auth_app_unitcouncilorchangerequest', ['original_unit_member_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24727_primary'))
    )
    op.create_index(op.f('idx_24727_auth_group_permissions_group_id_permission_id_0cd325b'), 'auth_group_permissions', ['group_id', 'permission_id'], unique=True)
    op.create_index(op.f('idx_24727_auth_group_permissio_permission_id_84c5c92e_fk_auth_p'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_table('kalamela_individualeventscorecard',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('awarded_mark', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('total_points', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('event_participation_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('added_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_participation_id'], ['kalamela_individualeventparticipation.id'], name=op.f('kalamela_individuale_event_participation__263c65ac_fk_kalamela_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_id'], ['auth_app_unitmembers.id'], name=op.f('kalamela_individuale_participant_id_43081941_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24843_primary'))
    )
    op.create_index(op.f('idx_24843_kalamela_individuale_participant_id_43081941_fk_auth_'), 'kalamela_individualeventscorecard', ['participant_id'], unique=False)
    op.create_index(op.f('idx_24843_kalamela_individuale_event_participation__263c65ac_fk'), 'kalamela_individualeventscorecard', ['event_participation_id'], unique=False)
    op.create_table('kalamela_groupeventscorecard',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('awarded_mark', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('added_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('chest_number', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('total_points', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24819_primary'))
    )
    op.create_table('kalamela_appealpayements',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('total_amount_to_pay', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('appeal_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appeal_id'], ['kalamela_appeal.id'], name=op.f('kalamela_appealpayem_appeal_id_e219c9cd_fk_kalamela_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24799_primary'))
    )
    op.create_index(op.f('idx_24799_kalamela_appealpayem_appeal_id_e219c9cd_fk_kalamela_'), 'kalamela_appealpayements', ['appeal_id'], unique=False)
    op.create_table('auth_app_unitname',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('auth_app_unitname_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('clergy_district_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clergy_district_id'], ['auth_app_clergydistrict.id'], name='auth_app_unitname_clergy_district_id_b4cf9464_fk_auth_app_', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='idx_24668_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_24668_auth_app_unitname_clergy_district_id_b4cf9464_fk_auth'), 'auth_app_unitname', ['clergy_district_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24779_primary'))
    )
    op.create_table('auth_group',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24722_primary'))
    )
    op.create_index(op.f('idx_24722_name'), 'auth_group', ['name'], unique=True)
    op.create_table('auth_app_unittransferrequest',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('proof', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_unit_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('destination_unit_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('unit_member_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('original_registered_user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_unit_id'], ['auth_app_unitname.id'], name=op.f('auth_app_unittransfe_current_unit_id_355b3b2b_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_unit_id'], ['auth_app_unitname.id'], name=op.f('auth_app_unittransfe_destination_unit_id_965f3375_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_registered_user_id'], ['auth_app_customuser.id'], name=op.f('auth_app_unittransfe_original_registered__5a4988e1_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_member_id'], ['auth_app_unitmembers.id'], name=op.f('auth_app_unittransfe_unit_member_id_82e1f938_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24715_primary'))
    )
    op.create_index(op.f('idx_24715_auth_app_unittransfe_unit_member_id_82e1f938_fk_auth_'), 'auth_app_unittransferrequest', ['unit_member_id'], unique=False)
    op.create_index(op.f('idx_24715_auth_app_unittransfe_original_registered__5a4988e1_fk'), 'auth_app_unittransferrequest', ['original_registered_user_id'], unique=False)
    op.create_index(op.f('idx_24715_auth_app_unittransfe_destination_unit_id_965f3375_fk_'), 'auth_app_unittransferrequest', ['destination_unit_id'], unique=False)
    op.create_index(op.f('idx_24715_auth_app_unittransfe_current_unit_id_355b3b2b_fk_auth'), 'auth_app_unittransferrequest', ['current_unit_id'], unique=False)
    op.create_table('conference_conferencepayment',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('proof', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('conference_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('amount_to_pay', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference_conference.id'], name=op.f('conference_conferenc_conference_id_f9c3fd7c_fk_conferenc'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['auth_app_customuser.id'], name=op.f('conference_conferenc_uploaded_by_id_177197ed_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24749_primary'))
    )
    op.create_index(op.f('idx_24749_conference_conferenc_uploaded_by_id_177197ed_fk_auth_'), 'conference_conferencepayment', ['uploaded_by_id'], unique=False)
    op.create_index(op.f('idx_24749_conference_conferenc_conference_id_f9c3fd7c_fk_confer'), 'conference_conferencepayment', ['conference_id'], unique=False)
    op.create_table('auth_app_archivedunitmember',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('qualification', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('registered_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['auth_app_customuser.id'], name=op.f('auth_app_archiveduni_registered_user_id_c46d5320_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24578_primary'))
    )
    op.create_index(op.f('idx_24578_auth_app_archiveduni_registered_user_id_c46d5320_fk_a'), 'auth_app_archivedunitmember', ['registered_user_id'], unique=False)
    op.create_table('auth_app_unitregistrationdata',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('registered_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['auth_app_customuser.id'], name=op.f('auth_app_unitregistr_registered_user_id_1dfbb9c6_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24710_primary'))
    )
    op.create_index(op.f('idx_24710_auth_app_unitregistr_registered_user_id_1dfbb9c6_fk_a'), 'auth_app_unitregistrationdata', ['registered_user_id'], unique=False)
    op.create_table('auth_app_unitdetails',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('registation_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('number_of_unit_members', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('registered_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['auth_app_customuser.id'], name=op.f('auth_app_unitdetails_registered_user_id_2cda4c7a_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24629_primary'))
    )
    op.create_index(op.f('idx_24629_auth_app_unitdetails_registered_user_id_2cda4c7a_fk_a'), 'auth_app_unitdetails', ['registered_user_id'], unique=False)
    op.create_table('conference_conference',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('conference_conference_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('added_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='idx_24737_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_app_unitofficialschangerequest',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('president_designation', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_president_designation', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('president_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_president_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('president_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_president_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('vice_president_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_vice_president_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('vice_president_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_vice_president_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('secretary_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_secretary_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('secretary_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_secretary_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('joint_secretary_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_joint_secretary_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('joint_secretary_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_joint_secretary_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('treasurer_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_treasurer_name', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('treasurer_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('original_treasurer_phone', sa.VARCHAR(length=50), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('proof', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('unit_official_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['unit_official_id'], ['auth_app_unitofficials.id'], name=op.f('auth_app_unitofficia_unit_official_id_02e242ed_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24681_primary'))
    )
    op.create_index(op.f('idx_24681_auth_app_unitofficia_unit_official_id_02e242ed_fk_aut'), 'auth_app_unitofficialschangerequest', ['unit_official_id'], unique=False)
    op.create_table('kalamela_appeal',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chest_number', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('statement', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reply', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('added_by_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['auth_app_unitmembers.id'], name=op.f('kalamela_appeal_added_by_id_c86c080e_fk_auth_app_unitmembers_id'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24791_primary'))
    )
    op.create_index(op.f('idx_24791_kalamela_appeal_added_by_id_c86c080e_fk_auth_app_unit'), 'kalamela_appeal', ['added_by_id'], unique=False)
    op.create_table('auth_app_customuser',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('auth_app_customuser_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('unit_name_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('clergy_district_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('conference_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('conference_member_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('conference_official_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clergy_district_id'], ['auth_app_clergydistrict.id'], name='auth_app_customuser_clergy_district_id_5c7bc652_fk_auth_app_', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conference_id'], ['conference_conference.id'], name='auth_app_customuser_conference_id_b982c4bf_fk_conferenc', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_name_id'], ['auth_app_unitname.id'], name='auth_app_customuser_unit_name_id_d460adf5_fk_auth_app_', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='idx_24591_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_24591_username'), 'auth_app_customuser', ['username'], unique=True)
    op.create_index(op.f('idx_24591_auth_app_customuser_unit_name_id_d460adf5_fk_auth_app'), 'auth_app_customuser', ['unit_name_id'], unique=False)
    op.create_index(op.f('idx_24591_auth_app_customuser_email_0f7acc77_uniq'), 'auth_app_customuser', ['email'], unique=True)
    op.create_index(op.f('idx_24591_auth_app_customuser_conference_id_b982c4bf_fk_confere'), 'auth_app_customuser', ['conference_id'], unique=False)
    op.create_index(op.f('idx_24591_auth_app_customuser_clergy_district_id_5c7bc652_fk_au'), 'auth_app_customuser', ['clergy_district_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name=op.f('idx_24785_primary'))
    )
    op.create_index(op.f('idx_24785_django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('auth_permission_content_type_id_2f476e4b_fk_django_co'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24732_primary'))
    )
    op.create_index(op.f('idx_24732_auth_permission_content_type_id_codename_01ab375a_uni'), 'auth_permission', ['content_type_id', 'codename'], unique=True)
    op.create_table('kalamela_groupevent',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('max_allowed_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('min_allowed_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('per_unit_allowed_limit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24805_primary'))
    )
    op.create_table('conference_conferencedelegate',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('conference_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('members_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('officials_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conference_conference.id'], name=op.f('conference_conferenc_conference_id_341b2b27_fk_conferenc'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['members_id'], ['auth_app_unitmembers.id'], name=op.f('conference_conferenc_members_id_fb62d2b7_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['officials_id'], ['auth_app_customuser.id'], name=op.f('conference_conferenc_officials_id_9a8b2622_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24744_primary'))
    )
    op.create_index(op.f('idx_24744_conference_conferenc_officials_id_9a8b2622_fk_auth_ap'), 'conference_conferencedelegate', ['officials_id'], unique=False)
    op.create_index(op.f('idx_24744_conference_conferenc_members_id_fb62d2b7_fk_auth_app_'), 'conference_conferencedelegate', ['members_id'], unique=False)
    op.create_index(op.f('idx_24744_conference_conferenc_conference_id_341b2b27_fk_confer'), 'conference_conferencedelegate', ['conference_id'], unique=False)
    op.create_table('kalamela_individualeventparticipation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chest_number', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('seniority_category', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('added_by_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('individual_event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['auth_app_customuser.id'], name=op.f('kalamela_individuale_added_by_id_55be7493_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['individual_event_id'], ['kalamela_individualevent.id'], name=op.f('kalamela_individuale_individual_event_id_d029d03b_fk_kalamela_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_id'], ['auth_app_unitmembers.id'], name=op.f('kalamela_individuale_participant_id_c03094b9_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24837_primary'))
    )
    op.create_index(op.f('idx_24837_kalamela_individuale_participant_id_c03094b9_fk_auth_'), 'kalamela_individualeventparticipation', ['participant_id'], unique=False)
    op.create_index(op.f('idx_24837_kalamela_individuale_individual_event_id_d029d03b_fk_'), 'kalamela_individualeventparticipation', ['individual_event_id'], unique=False)
    op.create_index(op.f('idx_24837_kalamela_individuale_added_by_id_55be7493_fk_auth_app'), 'kalamela_individualeventparticipation', ['added_by_id'], unique=False)
    op.create_table('auth_app_clergydistrict',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('auth_app_clergydistrict_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='idx_24586_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_app_unitcouncilor',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('registered_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('unit_member_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['auth_app_customuser.id'], name=op.f('auth_app_unitcouncil_registered_user_id_ea628aa8_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_member_id'], ['auth_app_unitmembers.id'], name=op.f('auth_app_unitcouncil_unit_member_id_e7f5e3b4_fk_auth_app_'), onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_24617_primary'))
    )
    op.create_index(op.f('idx_24617_auth_app_unitcouncil_unit_member_id_e7f5e3b4_fk_auth_'), 'auth_app_unitcouncilor', ['unit_member_id'], unique=False)
    op.create_index(op.f('idx_24617_auth_app_unitcouncil_registered_user_id_ea628aa8_fk_a'), 'auth_app_unitcouncilor', ['registered_user_id'], unique=False)
    op.drop_index(op.f('ix_unit_councilor_change_request_unit_councilor_id'), table_name='unit_councilor_change_request')
    op.drop_index(op.f('ix_unit_councilor_change_request_id'), table_name='unit_councilor_change_request')
    op.drop_table('unit_councilor_change_request')
    op.drop_index(op.f('ix_unit_transfer_request_unit_member_id'), table_name='unit_transfer_request')
    op.drop_index(op.f('ix_unit_transfer_request_id'), table_name='unit_transfer_request')
    op.drop_table('unit_transfer_request')
    op.drop_index(op.f('ix_unit_officials_change_request_unit_official_id'), table_name='unit_officials_change_request')
    op.drop_index(op.f('ix_unit_officials_change_request_id'), table_name='unit_officials_change_request')
    op.drop_table('unit_officials_change_request')
    op.drop_index(op.f('ix_unit_member_change_request_unit_member_id'), table_name='unit_member_change_request')
    op.drop_index(op.f('ix_unit_member_change_request_id'), table_name='unit_member_change_request')
    op.drop_table('unit_member_change_request')
    op.drop_index(op.f('ix_unit_member_add_request_registered_user_id'), table_name='unit_member_add_request')
    op.drop_index(op.f('ix_unit_member_add_request_id'), table_name='unit_member_add_request')
    op.drop_table('unit_member_add_request')
    op.drop_index(op.f('ix_removed_unit_member_registered_user_id'), table_name='removed_unit_member')
    op.drop_index(op.f('ix_removed_unit_member_id'), table_name='removed_unit_member')
    op.drop_table('removed_unit_member')
    op.drop_index(op.f('ix_food_preference_uploaded_by_id'), table_name='food_preference')
    op.drop_index(op.f('ix_food_preference_id'), table_name='food_preference')
    op.drop_index(op.f('ix_food_preference_conference_id'), table_name='food_preference')
    op.drop_table('food_preference')
    op.drop_index(op.f('ix_archived_unit_member_registered_user_id'), table_name='archived_unit_member')
    op.drop_index(op.f('ix_archived_unit_member_id'), table_name='archived_unit_member')
    op.drop_table('archived_unit_member')
    # ### end Alembic commands ###

