"""init"""

revision = '6480ae3b3a12'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clergy_district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_clergy_district_id'), 'clergy_district', ['id'], unique=False)
    op.create_table('conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conference_id'), 'conference', ['id'], unique=False)
    op.create_table('group_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('max_allowed_limit', sa.Integer(), nullable=False),
    sa.Column('min_allowed_limit', sa.Integer(), nullable=False),
    sa.Column('per_unit_allowed_limit', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group_event_score_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('awarded_mark', sa.Integer(), nullable=False),
    sa.Column('chest_number', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('login_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.CheckConstraint("username <> ''", name='ck_login_audit_username_nonempty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clergy_district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['clergy_district_id'], ['clergy_district.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clergy_district_id', 'name', name='uq_unit_name_per_district')
    )
    op.create_index(op.f('ix_unit_name_id'), 'unit_name', ['id'], unique=False)
    op.create_table('custom_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.Enum('ADMIN', 'UNIT', 'DISTRICT_OFFICIAL', name='usertype'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('unit_name_id', sa.Integer(), nullable=True),
    sa.Column('clergy_district_id', sa.Integer(), nullable=True),
    sa.Column('conference_member_count', sa.Integer(), nullable=True),
    sa.Column('conference_official_count', sa.Integer(), nullable=True),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clergy_district_id'], ['clergy_district.id'], ),
    sa.ForeignKeyConstraint(['unit_name_id'], ['unit_name.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_custom_user_email'), 'custom_user', ['email'], unique=True)
    op.create_index(op.f('ix_custom_user_id'), 'custom_user', ['id'], unique=False)
    op.create_index(op.f('ix_custom_user_username'), 'custom_user', ['username'], unique=True)
    op.create_table('conference_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('amount_to_pay', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('proof_path', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference_registration_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_official_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['district_official_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_official_id')
    )
    op.create_table('kalamela_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid_by_id', sa.Integer(), nullable=False),
    sa.Column('individual_events_count', sa.Integer(), nullable=False),
    sa.Column('group_events_count', sa.Integer(), nullable=False),
    sa.Column('total_amount_to_pay', sa.Integer(), nullable=False),
    sa.Column('payment_proof_path', sa.String(length=500), nullable=True),
    sa.Column('payment_status', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paid_by_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('registration_year', sa.Integer(), nullable=True),
    sa.Column('number_of_unit_members', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registered_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registered_user_id')
    )
    op.create_table('unit_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['registered_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_members_id'), 'unit_members', ['id'], unique=False)
    op.create_index(op.f('ix_unit_members_registered_user_id'), 'unit_members', ['registered_user_id'], unique=False)
    op.create_table('unit_officials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('president', sa.String(length=255), nullable=True),
    sa.Column('vice_president', sa.String(length=255), nullable=True),
    sa.Column('secretary', sa.String(length=255), nullable=True),
    sa.Column('joint_secretary', sa.String(length=255), nullable=True),
    sa.Column('treasurer', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['registered_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registered_user_id')
    )
    op.create_table('unit_registration_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registered_user_id')
    )
    op.create_table('appeal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('chest_number', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.String(length=1000), nullable=False),
    sa.Column('reply', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference_delegate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('officials_id', sa.Integer(), nullable=False),
    sa.Column('members_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['members_id'], ['unit_members.id'], ),
    sa.ForeignKeyConstraint(['officials_id'], ['custom_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conference_id', 'officials_id', name='uq_delegate_per_conf_official')
    )
    op.create_table('group_event_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_event_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('chest_number', sa.String(length=50), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['custom_user.id'], ),
    sa.ForeignKeyConstraint(['group_event_id'], ['group_event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_event_participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_event_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('chest_number', sa.String(length=50), nullable=True),
    sa.Column('seniority_category', sa.Enum('JUNIOR', 'SENIOR', name='senioritycategory'), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['custom_user.id'], ),
    sa.ForeignKeyConstraint(['individual_event_id'], ['individual_event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('individual_event_id', 'participant_id', name='uq_ind_event_per_participant')
    )
    op.create_table('kalamela_exclude_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('members_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['members_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('members_id')
    )
    op.create_table('unit_councilor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('unit_member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registered_user_id'], ['custom_user.id'], ),
    sa.ForeignKeyConstraint(['unit_member_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeal_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appeal_id', sa.Integer(), nullable=False),
    sa.Column('total_amount_to_pay', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=64), nullable=False),
    sa.Column('payment_status', sa.String(length=64), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appeal_id'], ['appeal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appeal_id')
    )
    op.create_table('individual_event_score_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_participation_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('awarded_mark', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_participation_id'], ['individual_event_participation.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['unit_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual_event_score_card')
    op.drop_table('appeal_payments')
    op.drop_table('unit_councilor')
    op.drop_table('kalamela_exclude_members')
    op.drop_table('individual_event_participation')
    op.drop_table('group_event_participation')
    op.drop_table('conference_delegate')
    op.drop_table('appeal')
    op.drop_table('unit_registration_data')
    op.drop_table('unit_officials')
    op.drop_index(op.f('ix_unit_members_registered_user_id'), table_name='unit_members')
    op.drop_index(op.f('ix_unit_members_id'), table_name='unit_members')
    op.drop_table('unit_members')
    op.drop_table('unit_details')
    op.drop_table('kalamela_payments')
    op.drop_table('conference_registration_data')
    op.drop_table('conference_payment')
    op.drop_index(op.f('ix_custom_user_username'), table_name='custom_user')
    op.drop_index(op.f('ix_custom_user_id'), table_name='custom_user')
    op.drop_index(op.f('ix_custom_user_email'), table_name='custom_user')
    op.drop_table('custom_user')
    op.drop_index(op.f('ix_unit_name_id'), table_name='unit_name')
    op.drop_table('unit_name')
    op.drop_table('login_audit')
    op.drop_table('individual_event')
    op.drop_table('group_event_score_card')
    op.drop_table('group_event')
    op.drop_index(op.f('ix_conference_id'), table_name='conference')
    op.drop_table('conference')
    op.drop_index(op.f('ix_clergy_district_id'), table_name='clergy_district')
    op.drop_table('clergy_district')
    # ### end Alembic commands ###

